"""fix mapping names

Revision ID: 176f0630bb8b
Revises: c6a8f927fbf4
Create Date: 2026-04-02 16:43:40.793104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '176f0630bb8b'
down_revision = 'c6a8f927fbf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enc_status', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('enc_created_at', sa.Text(), nullable=True))
        batch_op.drop_column('status')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enc_name', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('enc_email', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('enc_phone', sa.Text(), nullable=True))
        batch_op.drop_column('phone')
        batch_op.drop_column('name')
        batch_op.drop_column('email')

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enc_name', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('enc_description', sa.Text(), nullable=True))
        batch_op.drop_column('name')
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('enc_description')
        batch_op.drop_column('enc_name')

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('phone', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('enc_phone')
        batch_op.drop_column('enc_email')
        batch_op.drop_column('enc_name')

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('enc_created_at')
        batch_op.drop_column('enc_status')

    # ### end Alembic commands ###
