version: '3.8'

services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - notary_network

# Для локального запуску
  # backend:
  #   build: .
  #   container_name: notary_app-backend-1
  #   restart: always
  #   environment:
  #     DATABASE_URL: postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
  #     SECRET_KEY: ${SECRET_KEY}
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - db
  #   networks:
  #     - notary_network
# Для запуску на хмарі
backend:
    image: 331914066817.dkr.ecr.eu-west-1.amazonaws.com/notary-app-ecr-repo:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - notary_network

pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - notary_network

networks:
  notary_network:
    driver: bridge

volumes:
  postgres_data: