"""Add phone field final

Revision ID: 2a6f5d7867d1
Revises: 84021b9a2b60
Create Date: 2026-03-24 13:08:58.768614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a6f5d7867d1'
down_revision = '84021b9a2b60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archived_appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_phone', sa.Text(), nullable=True))

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('phone')

    with op.batch_alter_table('archived_appointment', schema=None) as batch_op:
        batch_op.drop_column('client_phone')

    # ### end Alembic commands ###
